# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    Unnecessary_const: true
    prefer_const_literals_to_create_immutables: true
    unused_local_variable: true
    unused_import: true
    
analyzer:
  errors:
    unused_import: error
    avoid_print: error
    prefer_const_constructors: error
    prefer_const_declarations: error
    Unnecessary_const: error
    prefer_const_literals_to_create_immutables: error
    unused_local_variable: error

  exclude:
    - 'lib/**/*.freezed.dart'
    - 'lib/**/*.g.dart'  
